CREATE DATABASE QLBANHANG
GO
USE QLBANHANG
GO

CREATE TABLE LOAISP
(
	MALOAI INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	URL TEXT,
)


CREATE TABLE NSX
(
	MANSX INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENNSX NVARCHAR(50) NOT NULL,
	URL TEXT,
)


CREATE TABLE SANPHAM
(
	MASP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	MOTA NTEXT ,
	HINHANH VARCHAR(MAX) ,
	NGAYCAPNHAT DATETIME NOT NULL,
	DONGIA INT NOT NULL,
	THANHTOANTRUCTIEP NVARCHAR(MAX),
	URL TEXT,
	MALOAI INT FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI) NOT NULL,
	MANSX INT FOREIGN KEY (MANSX) REFERENCES NSX(MANSX) NOT NULL,
)

CREATE TABLE KHACHHANG
(
	MAKH INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	DIACHI NTEXT NOT NULL,
	EMAIL TEXT NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASS VARCHAR(50) NOT NULL,
	NGAYDANGKY DATE NOT NULL
)


CREATE TABLE DONDATHANG
(
	MAD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NGAYDAT DATE NOT NULL,
	TENDAIDIEN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	DIACHIGIAO NTEXT NOT NULL,
	TINHTRANGTHANHTOAN bit,
	TINHTRANGGIAOHANG bit,
	MAKH INT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)

CREATE TABLE CTDDH
(
	MASP INT,
	MAD INT,
	DONGIA INT,
	SOLUONG INT,
	PRIMARY KEY (MASP,MAD),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	FOREIGN KEY (MAD) REFERENCES DONDATHANG(MAD),
)


CREATE TABLE ADMINLOGIN
(
	MAAD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENAD NVARCHAR(50) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	PASS VARCHAR(20) NOT NULL,
)

CREATE TABLE QUANGCAO
(
	MAQC INT PRIMARY KEY IDENTITY(1,1),
	HINHANH VARCHAR(MAX),
	LINK NTEXT,
	CLASS TEXT,
	ALT TEXT,
)
----LOAISP
INSERT INTO LOAISP (TENLOAI) VALUES (N'CHUỘT')
INSERT INTO LOAISP (TENLOAI) VALUES (N'BÀN PHÍM')
----NSX
INSERT INTO NSX (TENNSX) VALUES ('R8')
INSERT INTO NSX (TENNSX) VALUES ('RDRARS')
----SANPHAM
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('MOUSE R8 1613 LED','ahihi','mouse-r8-1613-led.jpg','1/22/2016','100000','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('KEYBOARD R8 1856 LED','ahihi','keyboard-r8-1856-led.jpg','8/14/2016','200000','2','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('KEYBOARD R8 A4 USB','ahihi','keyboard-r8-a4-usb.jpg','1/22/2016','100000','2','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('KEYBOARD R8 A3 LED','ahihi','keyboard-r8-a3-led.jpg','1/22/2016','100000','2','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,THANHTOANTRUCTIEP,MALOAI,MANSX) VALUES ('MOUSE R8 1618 LED','ahihi','mouse-r8-1618-led.jpg','1/22/2016','100000','<https://www.baokim.vn/payment/product/version11?business=luutrangminh%40gmail.com&id=&order_description=800%2F1200%2F1600%2F2400+DPI+6+key%2C+1+n%C3%BAt+cu%E1%BB%99n%2Cd%C3%A2y+d%C3%B9%0D%0A%C4%90%E1%BB%99+d%C3%A0i+d%C3%A2y%3A+150+%C2%B1+5cm%0D%0A%C4%90%C3%A8n+LED+%C4%91%E1%BB%95i+m%C3%A0u%0D%0AThi%E1%BA%BFt+k%E1%BA%BF+Gaming+&product_name=MOUSE+R8+1618+LED&product_price=134000&product_quantity=1&total_amount=134000&url_cancel=http%3A%2F%2Fthegioilinhkien.somee.com%2FTrangChu%2FXemChiTiet%2F5&url_detail=http%3A%2F%2Fthegioilinhkien.somee.com%2FTrangChu%2FXemChiTiet%2F5&url_success=http%3A%2F%2Fthegioilinhkien.somee.com%2FGioHang%2FThanhToanThanhCong"></a>','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('MOUSE R8 1628 LED','ahihi','mouse-r8-1628-led.jpg','1/22/2016','100000','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('MOUSE R8 1625 LED','ahihi','mouse-r8-1656-led.jpg','1/22/2016','100000','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX) VALUES ('KEYBOARD RDRAGS X19 GAME USB','ahihi','kb-rdrags-x19-game-usb.jpg','1/22/2016','100000','2','2')

------QUANGCAO
INSERT INTO QUANGCAO(HINHANH,LINK,CLASS,ALT) VALUES ('linh-kien-may-tinh.png','https://www.facebook.com','first-slide','First slide')
INSERT INTO QUANGCAO(HINHANH,LINK,CLASS,ALT) VALUES ('linh-kien-may-tinh-2.png','https://www.facebook.com','second-slide','Second slide')
INSERT INTO QUANGCAO(HINHANH,LINK,CLASS,ALT) VALUES ('s2.jpg','https://www.facebook.com','third-slide','Third slide')

