CREATE DATABASE QLBANHANG
GO
USE QLBANHANG
GO

CREATE TABLE LOAISP
(
	MALOAI INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENLOAI NVARCHAR(100) NOT NULL
)

CREATE TABLE NSX
(
	MANSX INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENNSX VARCHAR(100) NOT NULL
)

CREATE TABLE KHUYENMAI
(
	MAKM INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENKM NVARCHAR(100) NOT NULL,
	TYLEKM FLOAT NOT NULL,
)

CREATE TABLE SANPHAM
(
	MASP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENSP NVARCHAR(100) NOT NULL,
	MOTA NVARCHAR(300) NOT NULL,
	HINHANH VARCHAR(200) NOT NULL,
	NGAYCAPNHAT DATETIME NOT NULL,
	DONGIA INT NOT NULL,
	MALOAI INT FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI) NOT NULL,
	MANSX INT FOREIGN KEY (MANSX) REFERENCES NSX(MANSX) NOT NULL,
	MAKM INT FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM) NOT NULL
)

CREATE TABLE KHACHHANG
(
	MAKH INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TENKH NVARCHAR(100) NOT NULL,
	SDT CHAR(11) NOT NULL,
	DIACHI NVARCHAR(200) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	ID VARCHAR(100) NOT NULL,
	PASS VARCHAR(100) NOT NULL,
	NGAYDANGKY DATE NOT NULL
)


CREATE TABLE DONDATHANG
(
	MAD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NGAYDAT DATE NOT NULL,
	NGAYGIAO DATE NOT NULL,
	TENDAIDIEN NVARCHAR(100) NOT NULL,
	SDT CHAR(11) NOT NULL,
	DIACHIGIAO NVARCHAR(100) NOT NULL,
	TINHTRANGTHANHTOAN bit,
	TINHTRANGGIAOHANG bit,
	MAKH INT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)

CREATE TABLE CTDDH
(
	MASP INT,
	MAD INT,
	DONGIA INT,
	SOLUONG INT,
	PRIMARY KEY (MASP,MAD),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	FOREIGN KEY (MAD) REFERENCES DONDATHANG(MAD),
)

CREATE TABLE QUANGCAO
(
	MAQC INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	LINK VARCHAR(300) NOT NULL
)

CREATE TABLE ADMINLOGIN
(
	MAAD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	USERNAME CHAR(20),
	PASS CHAR(20)
)
----LOAISP
INSERT INTO LOAISP (TENLOAI) VALUES (N'CHUỘT')
INSERT INTO LOAISP (TENLOAI) VALUES (N'BÀN PHÍM')
----NSX
INSERT INTO NSX (TENNSX) VALUES ('R8')
INSERT INTO NSX (TENNSX) VALUES ('RDRARS')
----KHUYENMAI
INSERT INTO KHUYENMAI(TENKM,TYLEKM) VALUES ('KHONG GIAM','1')
INSERT INTO KHUYENMAI(TENKM,TYLEKM) VALUES ('GIAM 30%','0.3')
----SANPHAM
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('MOUSE R8 1613 LED','ahihi','mouse-r8-1613-led.jpg','1/22/2016','100000','1','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('KEYBOARD R8 1856 LED','ahihi','keyboard-r8-1856-led.jpg','8/14/2016','200000','2','1','2')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('KEYBOARD R8 A4 USB','ahihi','keyboard-r8-a4-usb.jpg','1/22/2016','100000','2','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('KEYBOARD R8 A3 LED','ahihi','keyboard-r8-a3-led.jpg','1/22/2016','100000','2','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('MOUSE R8 1618 LED','ahihi','mouse-r8-1618-led.jpg','1/22/2016','100000','1','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('MOUSE R8 1628 LED','ahihi','mouse-r8-1628-led.jpg','1/22/2016','100000','1','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('MOUSE R8 1625 LED','ahihi','mouse-r8-1656-led.jpg','1/22/2016','100000','1','1','1')
INSERT INTO SANPHAM(TENSP,MOTA,HINHANH,NGAYCAPNHAT,DONGIA,MALOAI,MANSX,MAKM) VALUES ('KEYBOARD RDRAGS X19 GAME USB','ahihi','kb-rdrags-x19-game-usb.jpg','1/22/2016','100000','2','2','1')