//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinhKienMayTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANGCAO
    {
        public int MAQC { get; set; }
        public string HINHANH { get; set; }
        public string LINK { get; set; }
        public string CLASS { get; set; }
        public string ALT { get; set; }
    }
}
